import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/nav";
import { ClientWalletProvider } from "@/components/ClientWalletProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OpenCharity",
  description: "Decentralized donation platform",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en">
      <body className={`${inter.className} antialiased dark`}>
        <ClientWalletProvider>
          <Navbar />
          {children}
        </ClientWalletProvider>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import "./globals.css";
// import { Inter } from "next/font/google";
// import Navbar from "@/components/nav";
// import { WalletProvider } from "@/contexts/WalletContext";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "opencharity",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${inter.className} antialiased dark`}>
//         <WalletProvider>
//           <Navbar />
//           {children}
//         </WalletProvider>
//       </body>
//     </html>
//   );
// }